In [2]:
import pandas as pd

In [3]:
pt = pd.read_csv('./practice_data/0813-bomin.csv')

### 데이터 있는 행만 보기

In [4]:
pt = pt[pd.notna(pt['날짜'])]

In [5]:
pt.head(10)

,날짜,기록 시간,기록자,호선,탑승역,하차역,붐빔 정도,노약자석 빈자리 여부,성별,비어있었던 역 수,연령대,뱃지 여부,임산부 여부,무거운 짐 여부,행동,기타 특이사항,짐 종류
0,2019. 7. 31,19:10,재민,5호선,공덕,여의도,N,NaN,여,NaN,중년,X,X,X,"이어폰, 핸드폰",NaN,"쇼핑백, 장우산"
1,2019. 7. 31,19:21,재민,9호선,여의도,신논현,F,NaN,여,NaN,중년,X,X,X,핸드폰,임산부석 비워달라는 방송이 나왔으나 아랑곳하지 않음,NaN
2,2019. 7. 31,19:28,재민,9호선,여의도,신논현,F,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
3,2019. 7. 31,19:32,재민,9호선,여의도,신논현,F,NaN,여,NaN,청년,X,O,X,핸드폰,NaN,NaN
4,2019. 7. 31,22:38,재민,분당선,선정릉,야탑,F,NaN,여,NaN,청년,O,O,X,"핸드폰, 대화",NaN,NaN
5,2019. 7. 31,22:42,재민,분당선,선정릉,야탑,F,NaN,남,NaN,중년,X,X,X,핸드폰,NaN,NaN
6,2019. 7. 31,18:30,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,NaN,옆자리가 나자 옮겨앉음,NaN
7,2019. 7. 31,18:30,보민,6호선,공덕,화랑대,N,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
8,2019. 7. 31,18:30,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,핸드폰,NaN,NaN
9,2019. 7. 31,18:30,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,NaN,금방 내림,NaN

### 데이터 갯수, 타입

In [6]:
len(pt)

564

In [7]:
pt.dtypes

날짜              object
기록 시간           object
기록자             object
호선              object
탑승역             object
하차역             object
붐빔 정도           object
노약자석 빈자리 여부     object
성별              object
비어있었던 역 수      float64
연령대             object
뱃지 여부           object
임산부 여부          object
무거운 짐 여부        object
행동              object
기타 특이사항         object
짐 종류            object
dtype: object

## 데이터 정제

1. 날짜, 시간 데이터 각각 타입에 맞게 바꿔주기

In [8]:
pt['날짜'] = pd.to_datetime(pt['날짜'])

In [9]:
pt.dtypes

날짜             datetime64[ns]
기록 시간                  object
기록자                    object
호선                     object
탑승역                    object
하차역                    object
붐빔 정도                  object
노약자석 빈자리 여부            object
성별                     object
비어있었던 역 수             float64
연령대                    object
뱃지 여부                  object
임산부 여부                 object
무거운 짐 여부               object
행동                     object
기타 특이사항                object
짐 종류                   object
dtype: object

In [10]:
pt['기록 시간'] = pd.to_datetime(pt['기록 시간'], format='%H:%M').dt.time

In [11]:
pt.dtypes

날짜             datetime64[ns]
기록 시간                  object
기록자                    object
호선                     object
탑승역                    object
하차역                    object
붐빔 정도                  object
노약자석 빈자리 여부            object
성별                     object
비어있었던 역 수             float64
연령대                    object
뱃지 여부                  object
임산부 여부                 object
무거운 짐 여부               object
행동                     object
기타 특이사항                object
짐 종류                   object
dtype: object

In [12]:
pt.head(20)

,날짜,기록 시간,기록자,호선,탑승역,하차역,붐빔 정도,노약자석 빈자리 여부,성별,비어있었던 역 수,연령대,뱃지 여부,임산부 여부,무거운 짐 여부,행동,기타 특이사항,짐 종류
0,2019-07-31,19:10:00,재민,5호선,공덕,여의도,N,NaN,여,NaN,중년,X,X,X,"이어폰, 핸드폰",NaN,"쇼핑백, 장우산"
1,2019-07-31,19:21:00,재민,9호선,여의도,신논현,F,NaN,여,NaN,중년,X,X,X,핸드폰,임산부석 비워달라는 방송이 나왔으나 아랑곳하지 않음,NaN
2,2019-07-31,19:28:00,재민,9호선,여의도,신논현,F,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
3,2019-07-31,19:32:00,재민,9호선,여의도,신논현,F,NaN,여,NaN,청년,X,O,X,핸드폰,NaN,NaN
4,2019-07-31,22:38:00,재민,분당선,선정릉,야탑,F,NaN,여,NaN,청년,O,O,X,"핸드폰, 대화",NaN,NaN
5,2019-07-31,22:42:00,재민,분당선,선정릉,야탑,F,NaN,남,NaN,중년,X,X,X,핸드폰,NaN,NaN
6,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,NaN,옆자리가 나자 옮겨앉음,NaN
7,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
8,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,핸드폰,NaN,NaN
9,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,NaN,금방 내림,NaN
10,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,남,NaN,노년,X,X,X,NaN,두자리에 걸터앉음. 지팡이,NaN
11,2019-07-31,18:47:00,단비,5호선,공덕,신길,F,NaN,여,NaN,청년,X,X,NaN,"이어폰, 핸드폰",NaN,크로스백 작은거
12,2019-07-31,18:47:00,단비,5호선,공덕,신길,F,NaN,여,NaN,중년,X,X,NaN,"이어폰, 잠",NaN,보스턴 백
13,2019-07-31,19:05:00,단비,1호선,신길,온수,N,X,여,NaN,중년,X,X,NaN,멍,NaN,보스턴 백
14,2019-07-31,19:05:00,단비,1호선,신길,온수,N,X,남,NaN,청년,X,X,NaN,"이어폰, 핸드폰",NaN,클러치
15,2019-07-31,19:15:00,단비,1호선,신길,온수,N,X,남,NaN,노년,X,X,NaN,멍,NaN,"크로스백, 종이가방 (파리바게트 (소) 크기"
16,2019-07-31,19:19:00,단비,1호선,개봉,온수,N,X,비었음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2019-07-31,19:27:00,단비,7호선,온수,신중동,F,X,여,NaN,청년,X,X,NaN,"이어폰, 핸드폰",NaN,크로스백
18,2019-07-31,19:27:00,단비,7호선,온수,신중동,F,X,여,NaN,청년,X,X,NaN,핸드폰 게임,NaN,에코백
19,2019-08-01,13:27:00,한솔,2호선,신림,신도림,E,O,여,NaN,중년,X,X,X,이어폰,일반석이 비어있음에도 불구하고 임산부석 착석,NaN

## 분석목표

0. 전체 앉아있던 사람들 중 임산부 비율

1. 어느 성별이 많이 앉는지

2. 무거운 짐과의 상관관계

3. 각 호선별로 평균 몇 구간이 비어있었는지

4. 어느 구간에서 가장 많이 비어있었는지

5. 각 호선별로 가장 많이 앉아있었던 사람의 성별과 나이대

6. 노년이 임산부석에 앉아있을 때 노약자석의 빈자리 여부의 상관관계

### 0. 전체 앉아있던 사람들 중 임산부 비율

In [13]:
empty = pt[pt['성별'] == '비었음']

In [14]:
not_empty = pt[pt['성별'] != '비었음']

In [15]:
len(empty)

162

In [16]:
len(not_empty)

402

In [17]:
len(pt) == len(empty) + len(not_empty)

True

In [18]:
pragnant = pt[(pt['성별'] != '비었음') & (pt['임산부 여부'] == 'O')]

In [19]:
len(pragnant)

21

In [20]:
f'임산부석 자리에 앉았던 {len(not_empty)}명 중 뱃지 유무로 또는 육안으로 구분 가능한 임산부는 {len(pragnant)}명이었습니다'

'임산부석 자리에 앉았던 402명 중 뱃지 유무로 또는 육안으로 구분 가능한 임산부는 21명이었습니다'

In [21]:
f'자리가 비어있지 않은 경우 중 명확히 구분 가능한 임산부가 앉아있는 비율은 {round(len(pragnant)/len(not_empty)*100,1)}% 입니다.'

'자리가 비어있지 않은 경우 중 명확히 구분 가능한 임산부가 앉아있는 비율은 5.2% 입니다.'

### 1. 어느 성별이 많이 앉는지

In [22]:
not_empty

,날짜,기록 시간,기록자,호선,탑승역,하차역,붐빔 정도,노약자석 빈자리 여부,성별,비어있었던 역 수,연령대,뱃지 여부,임산부 여부,무거운 짐 여부,행동,기타 특이사항,짐 종류
0,2019-07-31,19:10:00,재민,5호선,공덕,여의도,N,NaN,여,NaN,중년,X,X,X,"이어폰, 핸드폰",NaN,"쇼핑백, 장우산"
1,2019-07-31,19:21:00,재민,9호선,여의도,신논현,F,NaN,여,NaN,중년,X,X,X,핸드폰,임산부석 비워달라는 방송이 나왔으나 아랑곳하지 않음,NaN
2,2019-07-31,19:28:00,재민,9호선,여의도,신논현,F,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
3,2019-07-31,19:32:00,재민,9호선,여의도,신논현,F,NaN,여,NaN,청년,X,O,X,핸드폰,NaN,NaN
4,2019-07-31,22:38:00,재민,분당선,선정릉,야탑,F,NaN,여,NaN,청년,O,O,X,"핸드폰, 대화",NaN,NaN
5,2019-07-31,22:42:00,재민,분당선,선정릉,야탑,F,NaN,남,NaN,중년,X,X,X,핸드폰,NaN,NaN
6,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,NaN,옆자리가 나자 옮겨앉음,NaN
7,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
8,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,핸드폰,NaN,NaN
9,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,여,NaN,중년,X,X,X,NaN,금방 내림,NaN
10,2019-07-31,18:30:00,보민,6호선,공덕,화랑대,N,NaN,남,NaN,노년,X,X,X,NaN,두자리에 걸터앉음. 지팡이,NaN
11,2019-07-31,18:47:00,단비,5호선,공덕,신길,F,NaN,여,NaN,청년,X,X,NaN,"이어폰, 핸드폰",NaN,크로스백 작은거
12,2019-07-31,18:47:00,단비,5호선,공덕,신길,F,NaN,여,NaN,중년,X,X,NaN,"이어폰, 잠",NaN,보스턴 백
13,2019-07-31,19:05:00,단비,1호선,신길,온수,N,X,여,NaN,중년,X,X,NaN,멍,NaN,보스턴 백
14,2019-07-31,19:05:00,단비,1호선,신길,온수,N,X,남,NaN,청년,X,X,NaN,"이어폰, 핸드폰",NaN,클러치
15,2019-07-31,19:15:00,단비,1호선,신길,온수,N,X,남,NaN,노년,X,X,NaN,멍,NaN,"크로스백, 종이가방 (파리바게트 (소) 크기"
17,2019-07-31,19:27:00,단비,7호선,온수,신중동,F,X,여,NaN,청년,X,X,NaN,"이어폰, 핸드폰",NaN,크로스백
18,2019-07-31,19:27:00,단비,7호선,온수,신중동,F,X,여,NaN,청년,X,X,NaN,핸드폰 게임,NaN,에코백
19,2019-08-01,13:27:00,한솔,2호선,신림,신도림,E,O,여,NaN,중년,X,X,X,이어폰,일반석이 비어있음에도 불구하고 임산부석 착석,NaN
20,2019-08-01,13:27:00,한솔,2호선,신림,신도림,E,O,여,NaN,청년,O,O,X,핸드폰,NaN,NaN
21,2019-08-01,13:43:00,한솔,1호선,신도림,병점,F,X,남,NaN,노년,X,X,X,X,정신지체장애가 있는듯했음,NaN
22,2019-08-01,13:43:00,한솔,1호선,신도림,병점,F,X,여,NaN,청년,X,O,X,핸드폰,NaN,NaN
23,2019-08-01,11:20:00,재민,분당선,야탑,강남구청,F,X,여,NaN,중년,X,X,X,멍,NaN,"양산, 큰 비닐봉지"
24,2019-08-01,11:20:00,재민,분당선,야탑,강남구청,F,X,여,NaN,청년,X,X,X,잠,NaN,NaN
25,2019-08-01,11:30:00,재민,분당선,야탑,강남구청,F,X,여,NaN,어린이,X,X,X,멍,NaN,NaN
26,2019-08-01,11:44:00,재민,분당선,야탑,강남구청,F,X,여,NaN,중년,X,X,X,대화,4인가족 나란히 앉음,NaN
27,2019-08-01,11:53:00,재민,7호선,강남구청,중계,F,X,여,NaN,중년,X,X,O,핸드폰,NaN,큰 쇼핑백
28,2019-08-01,11:53:00,재민,7호선,강남구청,중계,F,X,여,NaN,중년,X,X,X,핸드폰,일반석이 빌 때마다 옮기려는 움직임,NaN
29,2019-08-01,12:01:00,재민,7호선,강남구청,중계,F,X,남,NaN,노년,X,X,X,멍,NaN,NaN
31,2019-08-01,12:11:00,재민,7호선,강남구청,중계,F,X,여,NaN,중년,X,X,X,대화,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,2019-08-13,08:00:00,한솔,1호선,병점,신길,N,O,여,NaN,노년,X,X,NaN,잠,NaN,백팩
525,2019-08-13,08:21:00,한솔,1호선,병점,신길,F,X,남,NaN,중년,X,X,X,"이어폰, 잠",앞에 임산부 있는데도 자서 옆사람이 자리내줌.......,NaN
526,2019-08-13,08:24:00,미현,1호선,수원,신길,F,X,남,NaN,중년,X,X,X,핸드폰,NaN,노트북 가방
527,2019-08-13,08:24:00,미현,1호선,수원,신길,F,X,여,NaN,중년,X,X,X,핸드폰,NaN,핸드백
528,2019-08-13,08:28:00,한솔,1호선,병점,신길,F,X,여,NaN,청년,X,X,NaN,핸드폰,NaN,"핸드백, 에코백"
529,2019-08-13,08:32:00,미현,1호선,수원,신길,F,X,여,NaN,노년,X,X,X,잠,NaN,핸드백
531,2019-08-13,08:49:00,한솔,1호선,병점,신길,F,X,여,NaN,청년,X,X,X,"핸드폰, 이어폰",NaN,NaN
532,2019-08-13,08:59:00,미현,1호선,수원,신길,F,X,남,NaN,중년,X,X,X,핸드폰,NaN,이마트 장바구니
533,2019-08-13,08:59:00,미현,1호선,수원,신길,F,X,여,NaN,중년,X,X,X,잠,NaN,핸드백
534,2019-08-13,09:11:00,한솔,5호선,신길,공덕,F,X,여,NaN,중년,X,X,X,"핸드폰, 이어폰",NaN,NaN
535,2019-08-13,09:12:00,한솔,5호선,신길,공덕,F,X,여,NaN,중년,X,X,NaN,"핸드폰, 이어폰",NaN,백팩
536,2019-08-13,09:10:00,미현,5호선,신길,공덕,F,X,여,NaN,중년,X,X,X,멍,NaN,핸드백
537,2019-08-13,09:10:00,미현,5호선,신길,공덕,F,X,남,NaN,중년,X,X,X,멍,NaN,크로스백
539,2019-08-13,08:42:00,재민,분당선,야탑,왕십리,F,X,여,NaN,중년,X,X,X,멍,한참 눈치 보다가 앉음,NaN
540,2019-08-13,08:42:00,재민,분당선,야탑,왕십리,F,X,여,NaN,청년,X,X,NaN,핸드폰,NaN,쇼핑백(중)
542,2019-08-13,09:28:00,재민,5호선,왕십리,공덕,N,X,여,NaN,중년,X,X,X,핸드폰,NaN,NaN
543,2019-08-13,09:28:00,재민,5호선,왕십리,공덕,N,X,여,NaN,중년,X,X,NaN,멍,NaN,백팩
545,2019-08-13,09:44:00,재민,5호선,왕십리,공덕,E,O,여,NaN,청년,O,O,X,핸드폰,옆자리에 있다가 임산부석이 비니까 옮김,NaN
546,2019-08-13,09:47:00,재민,5호선,왕십리,공덕,E,O,남,NaN,청년,X,X,NaN,대화,NaN,백팩
547,2019-08-13,18:56:00,한솔,5호선,공덕,신길,N,O,남,NaN,청년,X,X,X,"이어폰, 핸드폰",NaN,NaN
548,2019-08-13,18:57:00,한솔,5호선,공덕,신길,N,O,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
549,2019-08-13,19:13:00,한솔,1호선,신길,병점,N,O,여,NaN,청년,X,X,NaN,핸드폰,NaN,에코백
550,2019-08-13,19:25:00,한솔,1호선,신길,병점,F,O,여,NaN,청년,X,X,X,잠,외국인,NaN
552,2019-08-13,20:05:00,한솔,1호선,신길,병점,E,O,남,NaN,청년,X,X,NaN,"이어폰, 핸드폰",옆자리 비어있는데도 앉아있음,에코백
553,2019-08-13,20:07:00,한솔,1호선,신길,병점,E,O,여,NaN,청년,X,X,X,"핸드폰, 이어폰",일반자리 앉아있다가 임산부석 비니까 자리 옮김,NaN
556,2019-08-13,21:09:00,미현,1호선,신길,수원,F,X,남,NaN,노년,X,X,X,"핸드폰, 주변 살피기",NaN,NaN
558,2019-08-13,21:15:00,미현,1호선,신길,수원,F,X,여,NaN,중년,X,X,X,핸드폰,NaN,"핸드백, 커피"
559,2019-08-13,21:24:00,미현,1호선,신길,수원,F,X,여,NaN,중년,X,X,X,핸드폰,NaN,핸드백
562,2019-08-13,21:36:00,미현,1호선,수원,신길,F,X,여,NaN,청소년,X,X,X,친구와 대화,NaN,백팩
563,2019-08-13,21:36:00,미현,1호선,수원,신길,F,X,여,NaN,중년,X,X,X,멍,NaN,백팩

In [23]:
not_empty.groupby('성별')['성별'].count()

성별
남     92
여    310
Name: 성별, dtype: int64

#### +남성, 임산부인 여성과 아닌 여성 숫자 확인해보기

In [24]:
len(pragnant)

21

In [25]:
num_sex = pd.DataFrame(not_empty.groupby(['성별', '임산부 여부'])['날짜'].count()).rename(columns={'날짜': 'num'}).reset_index()

In [26]:
num_sex

  성별 임산부 여부  num
0  남      X   91
1  여      O   21
2  여      X  289

### 2. 무거운 짐과의 상관관계

In [27]:
heavy = not_empty[not_empty['무거운 짐 여부'] == 'O']

In [28]:
len(heavy)

20

In [29]:
f'임산부석 자리에 앉았던 {len(not_empty)}명 중 무거운 짐을 가지고 있었던 사람은 {len(heavy)}명이었습니다'

'임산부석 자리에 앉았던 402명 중 무거운 짐을 가지고 있었던 사람은 20명이었습니다'

In [30]:
f'자리가 비어있지 않은 경우 중 무거운 짐을 가진 사람이 앉은 비율은 {round(len(heavy)/len(not_empty)*100,1)}% 입니다.'

'자리가 비어있지 않은 경우 중 무거운 짐을 가진 사람이 앉은 비율은 5.0% 입니다.'

### 3. 각 호선별로 평균 몇 구간이 비어있었는지

In [31]:
empty_times = pd.DataFrame(empty.groupby(['호선', '날짜'])['기록 시간'].count()).rename(columns={'기록 시간': '빈 횟수'})

In [32]:
empty_times

                빈 횟수
호선  날짜
1호선 2019-07-31     1
    2019-08-02     3
    2019-08-03     6
    2019-08-05     9
    2019-08-07     8
    2019-08-08     3
    2019-08-09     6
    2019-08-12     8
    2019-08-13     5
5호선 2019-08-02     4
    2019-08-03     1
    2019-08-05     8
    2019-08-07     4
    2019-08-08    10
    2019-08-09     5
    2019-08-12     6
    2019-08-13     4
6호선 2019-08-02     1
    2019-08-03     7
    2019-08-05     8
    2019-08-07    11
    2019-08-08     5
    2019-08-09     3
7호선 2019-08-01     4
    2019-08-03     3
    2019-08-07     1
    2019-08-08     1
    2019-08-09     2
9호선 2019-08-09     3
분당선 2019-08-03     1
    2019-08-05     5
    2019-08-07     2
    2019-08-08     2
    2019-08-09     5
    2019-08-12     6
    2019-08-13     1

In [33]:
empty_tiems_sum = empty_times.groupby(['호선']).sum().reset_index()

In [34]:
empty_tiems_sum

    호선  빈 횟수
0  1호선    49
1  5호선    42
2  6호선    35
3  7호선    11
4  9호선     3
5  분당선    22

In [35]:
empty_total = pd.DataFrame(pd.to_numeric(empty.groupby('호선')['비어있었던 역 수'].sum(), downcast='signed')).reset_index()

In [36]:
empty_total

    호선  비어있었던 역 수
0  1호선        178
1  5호선        184
2  6호선        187
3  7호선         18
4  9호선          4
5  분당선        107

In [37]:
empty_total['하루평균빈자리'] = empty_total['비어있었던 역 수']/empty_tiems_sum['빈 횟수']

# 이렇게 해도 됨.
# empty_set = pd.DataFrame(pd.merge(empty_total, empty_tiems_sum)) 
# empty_set['비어있던 구간의 갯수/하루'] = empty_set['비어있었던 역 수']/empty_set['빈 횟수']

In [38]:
empty_total

    호선  비어있었던 역 수   하루평균빈자리
0  1호선        178  3.632653
1  5호선        184  4.380952
2  6호선        187  5.342857
3  7호선         18  1.636364
4  9호선          4  1.333333
5  분당선        107  4.863636

In [39]:
# 소수자리 어떻게 버리지...?

### 4. 어느 구간에서 가장 많이 비어있었는지

### 5. 각 호선별로 가장 많이 앉아있었던 사람의 성별과 나이대

### 6. 노년이 임산부석에 앉아있을 때 노약자석의 빈자리 여부의 상관관계